# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb5147840332b3240dcc322feec8d8cfc353c57606e0f2be0b5d336f972c241f57fb31e5a76ed98a8f557d3e75b7569618d658dee02bac4f8b83bd7992c61a3

test:
  secret_key_base: bc02c1c4e45ab3479c775a2373363b3808c7180ce0a742565461d540d874a55fef0312c6fe2596dea417ac04124fa5bc4ae7d6618cd37e5d0d45b9e3ec652c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
